### ISSUE TITLE
CoNLL-RDF @Docker

### ISSUE THREAD

**Issue by cfaeth** [acoli-repo/powla#2]
Please add manuall call to CoNLL-RDF compile.sh to the Dockerfile of [the python-server](https://github.com/acoli-repo/powla/blob/main/experimental/salt/swagger/python-server/Dockerfile)

(or grant me write access to this repo)

```
# clone CoNLL-RDF
RUN git clone https://github.com/acoli-repo/conll-rdf && \
    cd conll-rdf &&\
    ./compile.sh &&\
    echo | ./run.sh CoNLLStreamExtractor '#' ID
```

**Comment by chiarcos** [comment]
You can write now
